name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Tests on ${{ matrix.go-version }} ${{ matrix.platform }}
    strategy:
      matrix:
        go-version: ['1.26']
        platform: [ubuntu-latest, macos-latest, windows-2022, windows-11-arm]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM (Windows)
        if: runner.os == 'Windows'
        run: choco install llvm -y

      - name: Unzip libv8
        shell: bash
        run: |
          files=$(find . -name "libv8*.zip")
          for file in $files; do
            dir=$(dirname "$file")
            echo "Extracting $file to directory $dir"
            unzip -o -d "$dir" "$file"
          done

      - name: Go Test (Unix)
        if: runner.os != 'Windows'
        env:
          CGO_CXXFLAGS: "-Werror"
        run: go test -v -coverprofile c.out ./...

      - name: Go Test (Windows x64)
        if: runner.os == 'Windows' && runner.arch == 'X64'
        env:
          CGO_ENABLED: '1'
          CC: clang --target=x86_64-pc-windows-msvc -fuse-ld=lld
          CXX: clang++ --target=x86_64-pc-windows-msvc -fuse-ld=lld -fno-exceptions
        run: go test -v ./...

      - name: Go Test (Windows ARM64)
        if: runner.os == 'Windows' && runner.arch == 'ARM64'
        env:
          CGO_ENABLED: '1'
          CC: python ${{ github.workspace }}\deps\clang_arm64_cc.py
          CXX: python ${{ github.workspace }}\deps\clang_arm64_cxx.py
        run: go test -v ./...

      - name: Upload coverage to Codecov
        if: runner.os != 'Windows'
        uses: codecov/codecov-action@v1
        env:
          OS: ${{ matrix.platform }}
          GO: ${{ matrix.go-version }}
        with:
          files: ./c.out
          env_vars: OS,GO

      - name: Add GOPATH to GITHUB_ENV
        if: runner.os != 'Windows'
        run: echo "GOPATH=$(go env GOPATH)" >>"$GITHUB_ENV"

      - name: Scan and upload FOSSA data (Linux/Mac)
        if: runner.os != 'Windows' && env.FOSSA_API_KEY != '' && github.ref == 'refs/heads/master'
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash
          fossa analyze
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
